#

language: python

sudo: required

addons:
 apt:
  packages:
   - qemu-kvm
   - libvirt-bin
   - virtinst

services:
 - libvirt

before_install:
 - sudo apt-get install -y libvirt-bin virtinst
 - lsmod
 - dmesg
 - cat /proc/cpuinfo
 - virsh capabilities
 - curl -O http://cloud.centos.org/centos/7/images/CentOS-7-x86_64-GenericCloud-1509.qcow2
 - virt-install --virt-type qemu --network=user --graphics=none --noautoconsole --name testvm --ram=756 --vcpus=4 --os-type=linux --disk CentOS-7-x86_64-GenericCloud-1509.qcow2 --import
 - sleep 5
 - virsh list
 - virsh destroy testvm
 - virsh undefine testvm
