#

language: python

sudo: required

addons:
 apt:
  packages:
   - qemu-kvm
   - libvirt-bin
   - virtinst

services:
 - libvirt

before_install:
 - lsmod
 - dmesg
 - cat /proc/cpuinfo
 - virsh capabilities
 - virt-install --hvm --connect qemu:///session --network=user --pxe --graphics=none --noautoconsole --name pxe-test --ram=756 --vcpus=4 --os-type=linux --disk none
 - sleep 5
 - virsh list
 - virsh destroy pxe-test
 - virsh undefine pxe-test
